/* 
 * Fax.to REST API client for C#
 *
 * This is Fax.to REST API client for C#.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserManagementApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class UserManagementApiTests
    {
        private UserManagementApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UserManagementApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserManagementApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' UserManagementApi
            //Assert.IsInstanceOfType(typeof(UserManagementApi), instance, "instance is a UserManagementApi");
        }

        
        /// <summary>
        /// Test SubUserPost
        /// </summary>
        [Test]
        public void SubUserPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            // email = null;
            // password = null;
            //string apiKey = null;
            //var response = instance.SubUserPost(email, password, apiKey);
            //Assert.IsInstanceOf<InlineResponse2006> (response, "response is InlineResponse2006");
        }
        
        /// <summary>
        /// Test UserLoginPost
        /// </summary>
        [Test]
        public void UserLoginPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            // email = null;
            // password = null;
            //var response = instance.UserLoginPost(email, password);
            //Assert.IsInstanceOf<InlineResponse2005> (response, "response is InlineResponse2005");
        }
        
        /// <summary>
        /// Test UserPost
        /// </summary>
        [Test]
        public void UserPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            // email = null;
            // password = null;
            //var response = instance.UserPost(email, password);
            //Assert.IsInstanceOf<InlineResponse2005> (response, "response is InlineResponse2005");
        }
        
    }

}
