/* 
 * Fax.to REST API client for C#
 *
 * This is Fax.to REST API client for C#.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// InlineResponse20017Numbers
    /// </summary>
    [DataContract]
    public partial class InlineResponse20017Numbers :  IEquatable<InlineResponse20017Numbers>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20017Numbers" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="orderReference">orderReference.</param>
        /// <param name="countryCode">countryCode.</param>
        /// <param name="country">country.</param>
        /// <param name="cityName">cityName.</param>
        /// <param name="areaCode">areaCode.</param>
        /// <param name="didGroupId">didGroupId.</param>
        /// <param name="didNumber">didNumber.</param>
        /// <param name="expirationDate">expirationDate.</param>
        /// <param name="status">status.</param>
        public InlineResponse20017Numbers(int? id = default(int?), string orderReference = default(string), string countryCode = default(string), string country = default(string), string cityName = default(string), string areaCode = default(string), int? didGroupId = default(int?), string didNumber = default(string), DateTime? expirationDate = default(DateTime?), string status = default(string))
        {
            this.Id = id;
            this.OrderReference = orderReference;
            this.CountryCode = countryCode;
            this.Country = country;
            this.CityName = cityName;
            this.AreaCode = areaCode;
            this.DidGroupId = didGroupId;
            this.DidNumber = didNumber;
            this.ExpirationDate = expirationDate;
            this.Status = status;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets OrderReference
        /// </summary>
        [DataMember(Name="order_reference", EmitDefaultValue=false)]
        public string OrderReference { get; set; }

        /// <summary>
        /// Gets or Sets CountryCode
        /// </summary>
        [DataMember(Name="country_code", EmitDefaultValue=false)]
        public string CountryCode { get; set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [DataMember(Name="country", EmitDefaultValue=false)]
        public string Country { get; set; }

        /// <summary>
        /// Gets or Sets CityName
        /// </summary>
        [DataMember(Name="city_name", EmitDefaultValue=false)]
        public string CityName { get; set; }

        /// <summary>
        /// Gets or Sets AreaCode
        /// </summary>
        [DataMember(Name="area_code", EmitDefaultValue=false)]
        public string AreaCode { get; set; }

        /// <summary>
        /// Gets or Sets DidGroupId
        /// </summary>
        [DataMember(Name="did_group_id", EmitDefaultValue=false)]
        public int? DidGroupId { get; set; }

        /// <summary>
        /// Gets or Sets DidNumber
        /// </summary>
        [DataMember(Name="did_number", EmitDefaultValue=false)]
        public string DidNumber { get; set; }

        /// <summary>
        /// Gets or Sets ExpirationDate
        /// </summary>
        [DataMember(Name="expiration_date", EmitDefaultValue=false)]
        [JsonConverter(typeof(SwaggerDateConverter))]
        public DateTime? ExpirationDate { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse20017Numbers {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  OrderReference: ").Append(OrderReference).Append("\n");
            sb.Append("  CountryCode: ").Append(CountryCode).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  CityName: ").Append(CityName).Append("\n");
            sb.Append("  AreaCode: ").Append(AreaCode).Append("\n");
            sb.Append("  DidGroupId: ").Append(DidGroupId).Append("\n");
            sb.Append("  DidNumber: ").Append(DidNumber).Append("\n");
            sb.Append("  ExpirationDate: ").Append(ExpirationDate).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse20017Numbers);
        }

        /// <summary>
        /// Returns true if InlineResponse20017Numbers instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse20017Numbers to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20017Numbers input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.OrderReference == input.OrderReference ||
                    (this.OrderReference != null &&
                    this.OrderReference.Equals(input.OrderReference))
                ) && 
                (
                    this.CountryCode == input.CountryCode ||
                    (this.CountryCode != null &&
                    this.CountryCode.Equals(input.CountryCode))
                ) && 
                (
                    this.Country == input.Country ||
                    (this.Country != null &&
                    this.Country.Equals(input.Country))
                ) && 
                (
                    this.CityName == input.CityName ||
                    (this.CityName != null &&
                    this.CityName.Equals(input.CityName))
                ) && 
                (
                    this.AreaCode == input.AreaCode ||
                    (this.AreaCode != null &&
                    this.AreaCode.Equals(input.AreaCode))
                ) && 
                (
                    this.DidGroupId == input.DidGroupId ||
                    (this.DidGroupId != null &&
                    this.DidGroupId.Equals(input.DidGroupId))
                ) && 
                (
                    this.DidNumber == input.DidNumber ||
                    (this.DidNumber != null &&
                    this.DidNumber.Equals(input.DidNumber))
                ) && 
                (
                    this.ExpirationDate == input.ExpirationDate ||
                    (this.ExpirationDate != null &&
                    this.ExpirationDate.Equals(input.ExpirationDate))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.OrderReference != null)
                    hashCode = hashCode * 59 + this.OrderReference.GetHashCode();
                if (this.CountryCode != null)
                    hashCode = hashCode * 59 + this.CountryCode.GetHashCode();
                if (this.Country != null)
                    hashCode = hashCode * 59 + this.Country.GetHashCode();
                if (this.CityName != null)
                    hashCode = hashCode * 59 + this.CityName.GetHashCode();
                if (this.AreaCode != null)
                    hashCode = hashCode * 59 + this.AreaCode.GetHashCode();
                if (this.DidGroupId != null)
                    hashCode = hashCode * 59 + this.DidGroupId.GetHashCode();
                if (this.DidNumber != null)
                    hashCode = hashCode * 59 + this.DidNumber.GetHashCode();
                if (this.ExpirationDate != null)
                    hashCode = hashCode * 59 + this.ExpirationDate.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
