/* 
 * Fax.to REST API client for C#
 *
 * This is Fax.to REST API client for C#.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20014Areacodes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20014AreacodesTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20014Areacodes
        //private InlineResponse20014Areacodes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20014Areacodes
            //instance = new InlineResponse20014Areacodes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20014Areacodes
        /// </summary>
        [Test]
        public void InlineResponse20014AreacodesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20014Areacodes
            //Assert.IsInstanceOfType<InlineResponse20014Areacodes> (instance, "variable 'instance' is a InlineResponse20014Areacodes");
        }


        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'StateId'
        /// </summary>
        [Test]
        public void StateIdTest()
        {
            // TODO unit test for the property 'StateId'
        }
        /// <summary>
        /// Test the property 'AreaCode'
        /// </summary>
        [Test]
        public void AreaCodeTest()
        {
            // TODO unit test for the property 'AreaCode'
        }

    }

}
