/* 
 * Fax.to REST API client for C#
 *
 * This is Fax.to REST API client for C#.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20012Data
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20012DataTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20012Data
        //private InlineResponse20012Data instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20012Data
            //instance = new InlineResponse20012Data();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20012Data
        /// </summary>
        [Test]
        public void InlineResponse20012DataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20012Data
            //Assert.IsInstanceOfType<InlineResponse20012Data> (instance, "variable 'instance' is a InlineResponse20012Data");
        }


        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'Slug'
        /// </summary>
        [Test]
        public void SlugTest()
        {
            // TODO unit test for the property 'Slug'
        }
        /// <summary>
        /// Test the property 'A2Code'
        /// </summary>
        [Test]
        public void A2CodeTest()
        {
            // TODO unit test for the property 'A2Code'
        }
        /// <summary>
        /// Test the property 'DialCode'
        /// </summary>
        [Test]
        public void DialCodeTest()
        {
            // TODO unit test for the property 'DialCode'
        }

    }

}
