/* 
 * Fax.to REST API client for C#
 *
 * This is Fax.to REST API client for C#.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20017Numbers
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20017NumbersTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20017Numbers
        //private InlineResponse20017Numbers instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20017Numbers
            //instance = new InlineResponse20017Numbers();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20017Numbers
        /// </summary>
        [Test]
        public void InlineResponse20017NumbersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20017Numbers
            //Assert.IsInstanceOfType<InlineResponse20017Numbers> (instance, "variable 'instance' is a InlineResponse20017Numbers");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'OrderReference'
        /// </summary>
        [Test]
        public void OrderReferenceTest()
        {
            // TODO unit test for the property 'OrderReference'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'CityName'
        /// </summary>
        [Test]
        public void CityNameTest()
        {
            // TODO unit test for the property 'CityName'
        }
        /// <summary>
        /// Test the property 'AreaCode'
        /// </summary>
        [Test]
        public void AreaCodeTest()
        {
            // TODO unit test for the property 'AreaCode'
        }
        /// <summary>
        /// Test the property 'DidGroupId'
        /// </summary>
        [Test]
        public void DidGroupIdTest()
        {
            // TODO unit test for the property 'DidGroupId'
        }
        /// <summary>
        /// Test the property 'DidNumber'
        /// </summary>
        [Test]
        public void DidNumberTest()
        {
            // TODO unit test for the property 'DidNumber'
        }
        /// <summary>
        /// Test the property 'ExpirationDate'
        /// </summary>
        [Test]
        public void ExpirationDateTest()
        {
            // TODO unit test for the property 'ExpirationDate'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
