/* 
 * Fax.to REST API client for C#
 *
 * This is Fax.to REST API client for C#.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse20016Data
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse20016DataTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse20016Data
        //private InlineResponse20016Data instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse20016Data
            //instance = new InlineResponse20016Data();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse20016Data
        /// </summary>
        [Test]
        public void InlineResponse20016DataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse20016Data
            //Assert.IsInstanceOfType<InlineResponse20016Data> (instance, "variable 'instance' is a InlineResponse20016Data");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DidId'
        /// </summary>
        [Test]
        public void DidIdTest()
        {
            // TODO unit test for the property 'DidId'
        }
        /// <summary>
        /// Test the property 'DidGroupId'
        /// </summary>
        [Test]
        public void DidGroupIdTest()
        {
            // TODO unit test for the property 'DidGroupId'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'CityName'
        /// </summary>
        [Test]
        public void CityNameTest()
        {
            // TODO unit test for the property 'CityName'
        }
        /// <summary>
        /// Test the property 'AreaCode'
        /// </summary>
        [Test]
        public void AreaCodeTest()
        {
            // TODO unit test for the property 'AreaCode'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'TrunkId'
        /// </summary>
        [Test]
        public void TrunkIdTest()
        {
            // TODO unit test for the property 'TrunkId'
        }

    }

}
