/* 
 * Fax.to REST API client for C#
 *
 * This is Fax.to REST API client for C#.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2004MetaPaginationLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2004MetaPaginationLinksTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2004MetaPaginationLinks
        //private InlineResponse2004MetaPaginationLinks instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2004MetaPaginationLinks
            //instance = new InlineResponse2004MetaPaginationLinks();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2004MetaPaginationLinks
        /// </summary>
        [Test]
        public void InlineResponse2004MetaPaginationLinksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2004MetaPaginationLinks
            //Assert.IsInstanceOfType<InlineResponse2004MetaPaginationLinks> (instance, "variable 'instance' is a InlineResponse2004MetaPaginationLinks");
        }


        /// <summary>
        /// Test the property 'Previous'
        /// </summary>
        [Test]
        public void PreviousTest()
        {
            // TODO unit test for the property 'Previous'
        }
        /// <summary>
        /// Test the property 'Next'
        /// </summary>
        [Test]
        public void NextTest()
        {
            // TODO unit test for the property 'Next'
        }

    }

}
