/* 
 * Fax.to REST API client for C#
 *
 * This is Fax.to REST API client for C#.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2009
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2009Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2009
        //private InlineResponse2009 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2009
            //instance = new InlineResponse2009();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2009
        /// </summary>
        [Test]
        public void InlineResponse2009InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2009
            //Assert.IsInstanceOfType<InlineResponse2009> (instance, "variable 'instance' is a InlineResponse2009");
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Test]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Test]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }
        /// <summary>
        /// Test the property 'OrigFilename'
        /// </summary>
        [Test]
        public void OrigFilenameTest()
        {
            // TODO unit test for the property 'OrigFilename'
        }
        /// <summary>
        /// Test the property 'PreviewFile'
        /// </summary>
        [Test]
        public void PreviewFileTest()
        {
            // TODO unit test for the property 'PreviewFile'
        }
        /// <summary>
        /// Test the property 'PreviewImage'
        /// </summary>
        [Test]
        public void PreviewImageTest()
        {
            // TODO unit test for the property 'PreviewImage'
        }
        /// <summary>
        /// Test the property 'PreviewInStorage'
        /// </summary>
        [Test]
        public void PreviewInStorageTest()
        {
            // TODO unit test for the property 'PreviewInStorage'
        }
        /// <summary>
        /// Test the property 'FileExtension'
        /// </summary>
        [Test]
        public void FileExtensionTest()
        {
            // TODO unit test for the property 'FileExtension'
        }
        /// <summary>
        /// Test the property 'FilenameUploaded'
        /// </summary>
        [Test]
        public void FilenameUploadedTest()
        {
            // TODO unit test for the property 'FilenameUploaded'
        }
        /// <summary>
        /// Test the property 'Filesize'
        /// </summary>
        [Test]
        public void FilesizeTest()
        {
            // TODO unit test for the property 'Filesize'
        }
        /// <summary>
        /// Test the property 'S3'
        /// </summary>
        [Test]
        public void S3Test()
        {
            // TODO unit test for the property 'S3'
        }
        /// <summary>
        /// Test the property 'ServerDocumentId'
        /// </summary>
        [Test]
        public void ServerDocumentIdTest()
        {
            // TODO unit test for the property 'ServerDocumentId'
        }
        /// <summary>
        /// Test the property 'TeamUserId'
        /// </summary>
        [Test]
        public void TeamUserIdTest()
        {
            // TODO unit test for the property 'TeamUserId'
        }
        /// <summary>
        /// Test the property 'TotalPages'
        /// </summary>
        [Test]
        public void TotalPagesTest()
        {
            // TODO unit test for the property 'TotalPages'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
