/* 
 * Fax.to REST API client for C#
 *
 * This is Fax.to REST API client for C#.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: inquiries@fax.to
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2004Inbox
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2004InboxTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2004Inbox
        //private InlineResponse2004Inbox instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2004Inbox
            //instance = new InlineResponse2004Inbox();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2004Inbox
        /// </summary>
        [Test]
        public void InlineResponse2004InboxInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2004Inbox
            //Assert.IsInstanceOfType<InlineResponse2004Inbox> (instance, "variable 'instance' is a InlineResponse2004Inbox");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DidId'
        /// </summary>
        [Test]
        public void DidIdTest()
        {
            // TODO unit test for the property 'DidId'
        }
        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Test]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }
        /// <summary>
        /// Test the property 'Filesize'
        /// </summary>
        [Test]
        public void FilesizeTest()
        {
            // TODO unit test for the property 'Filesize'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Sender'
        /// </summary>
        [Test]
        public void SenderTest()
        {
            // TODO unit test for the property 'Sender'
        }
        /// <summary>
        /// Test the property 'TotalPages'
        /// </summary>
        [Test]
        public void TotalPagesTest()
        {
            // TODO unit test for the property 'TotalPages'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'PreviewFile'
        /// </summary>
        [Test]
        public void PreviewFileTest()
        {
            // TODO unit test for the property 'PreviewFile'
        }
        /// <summary>
        /// Test the property 'FileUrl'
        /// </summary>
        [Test]
        public void FileUrlTest()
        {
            // TODO unit test for the property 'FileUrl'
        }

    }

}
